appName: my-frontend

frontend:
  name: my-frontend

  service:
    type: NodePort
    port: 8080

  ingress:
    enabled: true
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: ""
      external-dns.alpha.kubernetes.io/hostname: ""
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/wafv2-acl-arn: ""
    hosts:
      - my-frontend.local

    tls: []
